version: '3.3'

services:
  scheduler-mongo:
    image: mongo
    volumes:
      - ~/scheduler-data/mongo/data:/data/db
    container_name: scheduler_mongo_container
    networks:
      - scheduler-network
    command: mongod --port 27018
    ports:
      - "27018:27018"
  scheduler:
    build:
      context: .
    image: tilie/scheduler:latest
    networks:
      - scheduler-network
    ports:
      - "8000:8000" # Make sure this port matches server.port in application_docker.properties, as well as the port in the global HOST variable in SchedulerApplication.java (src/main/java/scheduler)
    depends_on:
      - scheduler-mongo

networks:
  scheduler-network:
    driver: bridge